antora:
  extensions:
    - require: '@antora/lunr-extension'
      languages:
        - en

site:
  title: Marco Bungart
  start_page: about::index.adoc
  url: https://localhost:8080

content:
  sources:
    - url: ./
      branches:
        - HEAD
      start_path: components/about
    - url: ./
      branches:
        - HEAD
      start_path: components/articles
    - url: ./
      branches:
        - HEAD
      start_path: components/videos

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui

runtime:
  fetch: true

asciidoc:
  attributes:
    experimental: true
    kroki-fetch-diagram: true
    page-editable: false
    page-fileUri: false
    page-pagination: true@
    listing-caption: Listing
  extensions:
  - asciidoctor-kroki
  - '@asciidoctor/tabs'
