= About this blog

== Scope
I intend to use this blog in a variety of ways. Some posts will deal with my field of expertise - Software Engineering. Some posts may deal with a hobby of mine. Some may deal with questions and thoughts I have.

== Keywords
To keep things organized, all articles will have keywords associated with them. They are clearly visible in the article itself and searchable, although not explicitly. The blog uses link:https://antora.org/[Antora (`antora.org`)] to generate the pages, and the link:https://gitlab.com/antora/antora-lunr-extension[Antora Lunr extension (`gitlab.com`)] for site search. A corresponding link:https://gitlab.com/antora/antora-lunr-extension/-/issues/58[Issue (`gitlab.com`)] has been closed, but since then, no new release has been produced. So... it will come some time in the future 🙂.

== Methodology
Whenever applicable and feasible, I will include references. I will provide online links in the following format: the relevant part of the reference will be linked to the online source, and the domain will be listed in the display text in `monospace font`. For example link:https://www.google.com[this (`google.com`)] is a link to Google's home page. If a link does not have a domain after it, it is an internal link, i.e. it stays on this site (`turing85.github.io`).

I will strive to not delete essential parts of text. Instead, if I change my mind on something, or if new information arises, I will [line-through]#strike-through# line-through the relevant part. This way, my original text will still be visible. Furthermore, the page is backed by a link:https://github.com/turing85/turing85.github.io[public github repository (`github.com`)], thus the history is always accessible. This does not hold true for minor errors, like typos and alike. Those kind of changes will not be highlighted by line-through text (after all, I am known for typos and grammatical nonsense, and I would like to keep the blog readable 😆).

Furthermore, all articles will have a creation date and, if edited, a last modified date. I will not amend old post when new technological advancements render the statements wrong. If the topic is still interesting to me, I may write a new article, highlighting the differences (and most likely liking to the old one(s)).

I will try to do my due diligence. But please keep in mind that this is, after all, a private blog. It should be regarded as such. Whenever code projects are involved, I will post a link to the relevant code.

== Errors, Typos and the like
We are all humans, we all make mistakes. Sometimes smaller, sometimes larger. I am open to feedback. You are welcome to open an issue in the repository to point out something.

== Attribution
I do not want to get credit for things/ideas that are not mine. As such, I will always attribute content the original author(s). Likewise, the written content of this blog is copyrighted under link:https://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0 (`creativecommons.org`)]. You are welcome to share, remix, extend, juxtapose, criticise. The only thing I would ask of you is to attribute 😉.

== Disclaimer
This is my private blog. Opinions I express here are my own, and my own only. They do not reflect the opinion of my employer, friends family, ...

