name: Build PR

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: get-pr-number
        run: |
          echo "${{ github.event.number }}" > "pr-number.txt"
      - name: Upload PR number artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-number
          path: pr-number.txt
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Antora Build
        uses: ./.github/actions/antora-build