name: Destroy Preview

on:
  pull_request_target:
    types: [closed]

jobs:
  destroy-preview:
    name: Destroy Preview on surge.sh
    runs-on: ubuntu-latest
    steps:
      - name: Download pr-number artifact
        uses: actions/github-script@v4.2.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }}
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr-number"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr-number.zip', Buffer.from(download.data));
      - name: Unpackage pr-number Artifact
        run: |
          unzip pr-number.zip
      - name: Get PR number
        id: get-pr-number
        run: |
          echo "pr-number=$(cat pr-number.txt)" | tee "${GITHUB_OUTPUT}"
          rm -rf pr-number.txt
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Install surge
        run: npm install --global surge
      - name: Destroy PR ${{ steps.get-pr-number.outputs.pr-number }} from Surge
        run: surge teardown turing85-github-io-pr-${{ steps.get-pr-number.outputs.pr-number }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Delete PR status comment on success
        uses: actions-cool/maintain-one-comment@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.get-pr-number.outputs.pr-number }}
          delete: true
