name: Destroy Preview

on:
  pull_request_target:
    types: [closed]

jobs:
  destroy-preview:
    name: Destroy Preview on surge.sh
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install surge
        run: npm install --global surge
      - name: Destroy PR ${{ github.event.number }} from Surge
        run: surge teardown turing85-github-io-pr-${{ github.event.number }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Delete PR status comment on success
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          delete: true
